WIP [#72] Add support logtrace for Go SDK
extism/go-sdk pull request #73
Opened 2024-07-30 21:39 UTC by hilaryRope

## Description of the change
Add support for logtrace Go SDK

## Issue Reference
https://github.com/extism/go-sdk/issues/72 that is a logical step after [this](https://github.com/extism/go-pdk/issues/37)

## Checklist
- [] Documentation added/updated

2024-07-31 04:39 UTC, G4Vi requested changes
Overall, looks good, thank you! I'm just unsure about why `host.wasm` being regenerated. Changes may not be required with an explanation about it.

2024-07-31 04:39 UTC, G4Vi commented on wasm/host.wasm
Why regenerate this file? `host.go` doesn't look related. Was this done because the pdk was updated?

2024-07-31 08:10 UTC, hilaryRope commented on wasm/host.wasm
Thanks, no, I agree, this PR was still WIP, but made a mistake and did not set it to Draft. It is not needed here. I need to check the test failures as I am not quite sure why is that. I used [Modsurfer](https://modsurfer.dylibso.com/) to look into the generate `log.wasm` and I don't see the `log_trace` and I believe that is why the test is failing. Not quite sure why, though.

2024-07-31 14:19 UTC, G4Vi commented on wasm/host.wasm
No problem, the lack of `log_trace` does appear to be at least part of the problem, it appears changes need to be made to the Go PDK to make `log_trace` available there. For example, https://github.com/extism/go-pdk/blob/main/env.go, does not import it.

2024-07-31 14:24 UTC, hilaryRope commented on wasm/host.wasm
Indeed, I need to re-instate that first, leave it with me and will sort both. Thanks

2024-07-31 14:56 UTC, hilaryRope commented on wasm/host.wasm
And I was the one who removed it as a temporarily fix [here](https://github.com/extism/go-pdk/issues/37) :(

2024-08-07 18:31 UTC, hilaryRope commented on plugins/log/go.mod
> +require github.com/extism/go-pdk v1.0.7-0.20240804170849-7cb3d48ce7cc
pointing to this: https://github.com/extism/go-pdk/commit/7cb3d48ce7ccff27c3eab9edb251d56caabb5c18

2024-08-07 18:32 UTC, hilaryRope commented on wasm/host.wasm
@G4Vi changes made - I wanted to see the CICD running, but I see a message saying 1 `workflow awaiting approval`

2024-08-07 21:30 UTC, G4Vi commented on wasm/host.wasm
Workflow approved. https://github.com/extism/go-sdk/actions/runs/10289743772/job/28485520244?pr=73

2024-08-07 22:05 UTC, hilaryRope commented on wasm/host.wasm
@G4Vi thank you, bear with me, I will figure out what I am missing. Thanks

2024-08-19 14:10 UTC, nilslice commented
hey just pinging this thread to see if this is blocked by anything or if I can help move it along 🙂

2024-08-19 17:44 UTC, G4Vi commented
> hey just pinging this thread to see if this is blocked by anything or if I can help move it along 🙂

This was left on waiting for @hilaryRope to fix ci. If it isn't fixed soon we should potentially revert the pdk update.

2024-08-19 17:49 UTC, hilaryRope commented
> > hey just pinging this thread to see if this is blocked by anything or if I can help move it along 🙂
> 
> This was left on waiting for @hilaryRope to fix ci. If it isn't fixed soon we should potentially revert the pdk update.

Hi there, sorry but I have been away. I am referencing the latest commit with my change, but I seem to be getting the same test failures. I will need to check this. Can you give me a day, please? Unless, there is something very obvious about it. Thanks

2024-08-19 17:52 UTC, G4Vi commented
> > > hey just pinging this thread to see if this is blocked by anything or if I can help move it along 🙂
> > 
> > 
> > This was left on waiting for @hilaryRope to fix ci. If it isn't fixed soon we should potentially revert the pdk update.
> 
> Hi there, sorry but I have been away. I am referencing the latest commit with my change, but I seem to be getting the same test failures. I will need to check this. Can you give me a day, please? Unless, there is something very obvious about it. Thanks

Sure thing, thanks for the update!

2024-08-19 18:53 UTC, nilslice commented
No rush at all :) didnt want this to get left behind in case it was waiting on something from our end.

2024-08-20 16:38 UTC, hilaryRope commented
> No rush at all :) didnt want this to get left behind in case it was waiting on something from our end.

@nilslice  Noo, you and @G4Vi are absolutely right and it has been on the back of my mind for a bit. I am scratching my head, perhaps stupidly, as I am pointing to the correct sha in the go-pdk where the trace has been re-instante and still I am getting a failure in https://github.com/extism/go-sdk/blob/9748ea03f3dc755a575a3bdc6aa3fa7573b745ac/extism_test.go#L455. I wonder if you can have a quick check as I probably missing something trivial here. Thank you

2024-08-20 16:43 UTC, nilslice commented
Thanks, @hilaryRope! I'll run CI and see what happens, and can investigate today too

2024-08-28 19:45 UTC, nilslice commented
@hilaryRope @G4Vi - i'm going to merge this and make the tweaks from a new branch, as I am working on some related changes that may make this PR harder to merge later. 

The test looks ok, and I think it's just a problem finding the package at the ref. In any case, I won't tag a new release until all of this is sorted so these changes shouldn't impact anyone using the SDK.

2024-08-28 19:47 UTC, merged

2024-08-28 20:37 UTC, hilaryRope commented
> @hilaryRope @G4Vi - i'm going to merge this and make the tweaks from a new branch, as I am working on some related changes that may make this PR harder to merge later.
> 
> The test looks ok, and I think it's just a problem finding the package at the ref. In any case, I won't tag a new release until all of this is sorted so these changes shouldn't impact anyone using the SDK.

Thank you for this, appreciated!